name: mangue-bem

on:
  push:
    branches:
      - 'master'
      - 'feature/ci'
  pull_request:
    branches:
      - 'master'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Run the Maven verify phase
      run: mvn --batch-mode --update-snapshots verify
    - name: Build with Maven
      run: mvn -B package --file pom.xml
